import test from 'node:test';
import assert from 'node:assert/strict';
import { TYPE, DEFAULT_SCENARIO, buildDiagram, wallingDiagram, substitute, validate, run,
  scenarioInputs, interpret, finiteScenarios, checkEquivalence } from '../apps/wall-roof-wiring-smc/model.mjs';

const copy = value => structuredClone(value);
const endpoint = (wire, side, node, port) => wire[side][0] === node && wire[side][1] === port;
const checkReject = (diagram, pattern) => {
  const checked = validate(diagram);
  assert.equal(checked.ok, false);
  assert.ok(checked.issues.some(issue => pattern.test(issue)), checked.issues.join('\n'));
  assert.equal(run(diagram).ok, false);
  assert.deepEqual(run(diagram).outputs, {});
  return checked;
};

test('both renderings are well formed and have identical actual boundaries', () => {
  const expanded = buildDiagram(), collapsed = buildDiagram({ expanded: false });
  for (const diagram of [expanded, collapsed]) {
    assert.deepEqual(validate(diagram).issues, []);
    assert.equal(new Set(validate(diagram).order).size, diagram.boxes.length);
    for (const port of [...diagram.inputs, ...diagram.outputs]) assert.ok(TYPE[port.type]);
  }
  assert.deepEqual(expanded.inputs, collapsed.inputs);
  assert.deepEqual(expanded.outputs, collapsed.outputs);
  assert.equal(expanded.boxes.some(box => box.rule === 'compound'), false);
  assert.equal(collapsed.boxes.find(box => box.id === 'walling').rule, 'compound');
});

test('expanded diagram is generated by generic substitution of the real inner diagram', () => {
  const collapsed = buildDiagram({ expanded: false });
  const inner = collapsed.boxes.find(box => box.id === 'walling').diagram;
  const spliced = substitute(collapsed, 'walling', inner);
  const expanded = buildDiagram();
  assert.deepEqual(spliced.boxes, expanded.boxes);
  assert.deepEqual(spliced.wires, expanded.wires);
  assert.equal(spliced.boxes.filter(box => box.id.startsWith('walling/')).length, 4);
  assert.ok(spliced.wires.some(wire => endpoint(wire, 'from', 'walling/wall', 'wall') && endpoint(wire, 'to', 'ready', 'wall')));
});

test('substitution also splices direct identity wires and leaves the original intact', () => {
  const ports = [{ id: 'worker', type: 'BL', label: 'worker' }];
  const identity = { inputs: copy(ports), outputs: copy(ports), boxes: [],
    wires: [{ from: ['IN', 'worker'], to: ['OUT', 'worker'] }] };
  const outer = { inputs: copy(ports), outputs: copy(ports), boxes: [{ id: 'slot', label: 'Identity slot',
    rule: 'compound', inputs: copy(ports), outputs: copy(ports), diagram: identity }],
    wires: [{ from: ['IN', 'worker'], to: ['slot', 'worker'] }, { from: ['slot', 'worker'], to: ['OUT', 'worker'] }] };
  const before = copy(outer), inserted = substitute(outer, 'slot', identity);
  assert.deepEqual(outer, before);
  assert.deepEqual(inserted.boxes, []);
  assert.deepEqual(inserted.wires, identity.wires);
  const input = { worker: { type: 'BL', id: 'person-01' } };
  assert.deepEqual(interpret(outer, input).outputs, interpret(inserted, input).outputs);
});

test('substitution rejects an otherwise valid replacement with the wrong interface', () => {
  const outer = buildDiagram({ expanded: false }), inner = wallingDiagram();
  inner.inputs[0].id = 'other-worker';
  inner.wires.find(wire => endpoint(wire, 'from', 'IN', 'mixer')).from[1] = 'other-worker';
  assert.equal(validate(inner).ok, true);
  assert.throws(() => substitute(outer, 'walling', inner), /same ordered input and output/);
});

test('linear multiplicity catches one worker output wired to two consumers', () => {
  for (const expanded of [true, false]) {
    const result = checkReject(buildDiagram({ expanded, fault: 'duplicate-worker' }), /IN\.mixer has 2 attachments/);
    assert.ok(result.issues.some(issue => /IN\.builder has 0 attachments/.test(issue)));
  }
});

test('the missing-wire case finds both a free source and an unfilled target', () => {
  for (const expanded of [true, false]) {
    const result = checkReject(buildDiagram({ expanded, fault: 'missing-wire' }), /Source IN\.sand has 0 attachments/);
    assert.ok(result.issues.some(issue => /Target .*sand has 0 attachments/.test(issue)));
  }
});

test('type swapping preserves attachment counts but fails type equality', () => {
  for (const expanded of [true, false]) {
    const result = checkReject(buildDiagram({ expanded, fault: 'wrong-type' }), /Type mismatch/);
    assert.equal(result.issues.filter(issue => /Type mismatch/.test(issue)).length, 2);
    assert.equal(result.issues.some(issue => /attachments/.test(issue)), false);
  }
});

test('bypassing readiness rejects the actual BuiltWall to ReadyWall wire', () => {
  for (const expanded of [true, false]) {
    const result = checkReject(buildDiagram({ expanded, fault: 'bypass-readiness' }), /BuiltWall.*ReadyWall/);
    assert.ok(result.issues.some(issue => /Source ready\.wall has 0 attachments/.test(issue)));
  }
});

test('fan-in violates target multiplicity even when every source has one attachment', () => {
  const diagram = buildDiagram();
  diagram.wires.find(wire => endpoint(wire, 'from', 'IN', 'builder')).to = ['walling/mix', 'mixer'];
  const result = checkReject(diagram, /Target walling\/mix\.mixer has 2 attachments/);
  assert.equal(result.issues.some(issue => /^Source .*attachments/.test(issue)), false);
});

test('wrong direction, dangling endpoint and malformed wires are distinguished', () => {
  const wrongDirection = buildDiagram();
  wrongDirection.wires[0].from = ['OUT', 'shell'];
  checkReject(wrongDirection, /wrong direction/);
  const dangling = buildDiagram();
  dangling.wires[0].to = ['ghost', 'not-a-port'];
  checkReject(dangling, /dangling target endpoint/);
  const malformed = buildDiagram();
  malformed.wires[0].from = ['IN'];
  checkReject(malformed, /malformed endpoints/);
});

test('IDs must be present and unique, and outer boundary IDs are reserved', () => {
  const duplicateBox = buildDiagram();
  duplicateBox.boxes.push(copy(duplicateBox.boxes[0]));
  checkReject(duplicateBox, /Duplicate box ID/);
  const duplicatePort = buildDiagram();
  duplicatePort.inputs.push(copy(duplicatePort.inputs[0]));
  checkReject(duplicatePort, /duplicate input port ID/);
  const emptyID = buildDiagram(); emptyID.boxes[0].id = '';
  checkReject(emptyID, /missing or invalid ID/);
  const reserved = buildDiagram(); reserved.boxes[0].id = 'IN';
  checkReject(reserved, /reserved/);
});

test('unknown types and incorrect compound interfaces are syntactic defects', () => {
  const unknown = buildDiagram(); unknown.inputs[0].type = 'FreePeople';
  checkReject(unknown, /unknown type/);
  const mismatch = buildDiagram({ expanded: false });
  mismatch.boxes.find(box => box.id === 'walling').inputs.reverse();
  checkReject(mismatch, /compound boundary does not match/);
});

test('a resource feedback cycle fails independently of type and multiplicity checks', () => {
  const diagram = buildDiagram();
  const workerIn = diagram.wires.find(wire => endpoint(wire, 'from', 'IN', 'builder'));
  const workerOut = diagram.wires.find(wire => endpoint(wire, 'to', 'OUT', 'builder'));
  [workerIn.to, workerOut.to] = [workerOut.to, workerIn.to];
  const result = checkReject(diagram, /Directed cycle/);
  assert.equal(result.issues.some(issue => /Type mismatch|attachments/.test(issue)), false);
});

test('a box feeding its own correctly typed input is a directed cycle', () => {
  const port = { id: 'resource', type: 'BL', label: 'Resource' };
  checkReject({ inputs: [], outputs: [], boxes: [{ id: 'loop', label: 'Loop', rule: 'unknown', inputs: [port], outputs: [port] }],
    wires: [{ from: ['loop', 'resource'], to: ['loop', 'resource'] }] }, /Directed cycle/);
});

test('recursive compounds are rejected instead of recursing forever', () => {
  const diagram = { inputs: [], outputs: [], boxes: [], wires: [] };
  diagram.boxes.push({ id: 'recurse', label: 'Recursive', rule: 'compound', inputs: [], outputs: [], diagram });
  checkReject(diagram, /not finite/);
});

test('collapsed and expanded relations agree for every bounded fixture, including rejection', () => {
  assert.equal(finiteScenarios().length, 256);
  assert.deepEqual(checkEquivalence(), { ok: true, checked: 256, accepted: 2, rejected: 254, failures: [] });
  assert.deepEqual(checkEquivalence('strict'), { ok: true, checked: 256, accepted: 1, rejected: 255, failures: [] });
});

test('same typed interface does not imply same behaviour', () => {
  const standard = buildDiagram(), strict = buildDiagram({ replacement: 'strict' });
  assert.deepEqual(standard.inputs, strict.inputs);
  assert.deepEqual(standard.outputs, strict.outputs);
  assert.equal(validate(strict).ok, true);
  assert.equal(run(standard).ok, true);
  assert.equal(run(strict).ok, false);
  assert.match(run(strict).errors.join(' '), /requires drawing revision B/);
  const revised = { ...DEFAULT_SCENARIO, revision: 'B', evidenceRevision: 'B' };
  assert.equal(run(strict, revised).ok, true);
  assert.deepEqual(run(standard, revised).outputs, run(strict, revised).outputs);
});

test('distinct workers are an explicit primitive relation, not a type distinction', () => {
  const diagram = buildDiagram();
  assert.equal(diagram.inputs.find(port => port.id === 'mixer').type, 'BL');
  assert.equal(diagram.inputs.find(port => port.id === 'builder').type, 'BL');
  assert.equal(validate(diagram).ok, true);
  const result = run(diagram, { sameWorker: true });
  assert.equal(result.ok, false);
  assert.match(result.errors.join(' '), /distinct resource instances/);
  assert.deepEqual(result.outputs, {});
  assert.ok(result.trace.some(row => row.id === 'walling/crew' && row.status === 'fail'));
});

test('worker premise survives substitution without relying on an outer special case', () => {
  const collapsed = buildDiagram({ expanded: false });
  delete collapsed.premises;
  const walling = collapsed.boxes.find(box => box.id === 'walling');
  const expanded = substitute(collapsed, 'walling', walling.diagram);
  const alias = { sameWorker: true };
  assert.equal(run(collapsed, alias).ok, false);
  assert.equal(run(expanded, alias).ok, false);
  assert.deepEqual(run(collapsed, alias).outputs, run(expanded, alias).outputs);
  assert.ok(expanded.boxes.some(box => box.id === 'walling/crew' && box.rule === 'crew'));
  assert.equal(Object.hasOwn(collapsed, 'premises'), false);
  assert.equal(Object.hasOwn(walling.diagram, 'premises'), false);
});

test('each concrete condition can reject a syntactically valid diagram', () => {
  const diagram = buildDiagram();
  const cases = [
    [{ accessOK: false }, 'access'], [{ mortarOK: false }, 'walling/mix'],
    [{ geometryOK: false }, 'walling/wall'], [{ released: false }, 'ready'],
    [{ roofFits: false }, 'roof'], [{ evidenceRevision: 'B' }, 'ready'],
    [{ evidenceGeometry: 'other-wall' }, 'ready']
  ];
  assert.equal(validate(diagram).ok, true);
  for (const [scenario, id] of cases) {
    const result = run(diagram, scenario);
    assert.equal(result.ok, false, JSON.stringify(scenario));
    assert.ok(result.trace.some(row => row.id === id && row.status === 'fail'), JSON.stringify(scenario));
    assert.deepEqual(result.outputs, {});
    assert.equal(run(buildDiagram({ expanded: false }), scenario).ok, false);
  }
});

test('rejected inputs create no full-boundary tuple, and downstream boxes are blocked', () => {
  const result = run(buildDiagram(), { mortarOK: false });
  assert.ok(result.trace.some(row => row.id === 'walling/set' && row.status === 'pass'));
  assert.ok(result.trace.some(row => row.id === 'walling/wall' && row.status === 'blocked'));
  assert.ok(result.trace.some(row => row.id === 'roof' && row.status === 'blocked'));
  assert.deepEqual(result.outputs, {});
});

test('workers, peg kit, drawing and access are retained; roof materials enter the shell', () => {
  for (const expanded of [true, false]) {
    const input = scenarioInputs(), result = interpret(buildDiagram({ expanded }), input);
    assert.equal(result.ok, true);
    for (const id of ['mixer', 'builder', 'peg', 'drawing']) assert.equal(result.outputs[id], input[id]);
    assert.equal(result.outputs.access.id, input.access.id);
    assert.equal(result.outputs.access.type, 'Sc');
    assert.equal(result.outputs.access.checked, true);
    assert.equal(result.outputs.shell.roofkit, input.roofkit);
    assert.deepEqual(result.outputs.shell.roofkit.contents, ['trusses', 'coverings', 'fasteners']);
    assert.equal(result.outputs.shell.wall.type, 'BuiltWall');
    assert.match(result.outputs.shell.wall.scope, /whole prepared one-storey/);
    assert.match(result.outputs.shell.scope, /weatherproofing outside/);
    assert.deepEqual(Object.keys(result.outputs).sort(), ['access', 'builder', 'drawing', 'mixer', 'peg', 'shell']);
  }
});

test('access is supplied before walling and threaded through walling and roof', () => {
  const diagram = buildDiagram();
  assert.equal(diagram.inputs.find(port => port.id === 'access').type, 'ScRaw');
  assert.ok(diagram.wires.some(wire => endpoint(wire, 'from', 'access', 'access') && endpoint(wire, 'to', 'walling/wall', 'access')));
  assert.ok(diagram.wires.some(wire => endpoint(wire, 'from', 'walling/wall', 'access') && endpoint(wire, 'to', 'roof', 'access')));
  assert.ok(diagram.wires.some(wire => endpoint(wire, 'from', 'roof', 'access') && endpoint(wire, 'to', 'OUT', 'access')));
});

test('nested execution actually uses its internal rules', () => {
  const diagram = buildDiagram({ expanded: false });
  const inner = diagram.boxes.find(box => box.id === 'walling').diagram;
  inner.boxes.find(box => box.id === 'set').rule = 'set-strict';
  assert.equal(validate(diagram).ok, true);
  const rejected = run(diagram);
  assert.equal(rejected.ok, false);
  assert.ok(rejected.trace.some(row => row.id === 'walling/set' && row.status === 'fail'));
  assert.equal(run(diagram, { revision: 'B', evidenceRevision: 'B' }).ok, true);
});

test('interpretation requires boundary values of the declared types', () => {
  const input = scenarioInputs(); delete input.sand;
  assert.match(interpret(buildDiagram(), input).errors.join(' '), /Missing boundary value sand/);
  input.sand = { type: 'C', id: 'pretend-sand' };
  assert.match(interpret(buildDiagram(), input).errors.join(' '), /sand does not have type S/);
});

test('running the model never mutates the supplied diagram or scenario', () => {
  const diagram = buildDiagram(), scenario = { ...DEFAULT_SCENARIO };
  const originalDiagram = copy(diagram), originalScenario = copy(scenario);
  run(diagram, scenario);
  assert.deepEqual(diagram, originalDiagram);
  assert.deepEqual(scenario, originalScenario);
});
