import {TYPE,DEFAULT_SCENARIO,buildDiagram,validate,run,checkEquivalence} from './model.mjs';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected='walling';
let current;
const fields=['accessOK','mortarOK','geometryOK','released','roofFits','sameWorker'];
function endpointLabel(endpoint){const [id,port]=endpoint;return `${id==='IN'?'Supplied':id==='OUT'?'Returned':current.boxes.find(b=>b.id===id)?.label??id} · ${port}`;}
function typeAt(endpoint){const [id,port]=endpoint;return (id==='IN'?current.inputs:current.boxes.find(b=>b.id===id)?.outputs??[]).find(p=>p.id===port)?.type??'?';}
function inspect(id){selected=id;const b=current.boxes.find(b=>b.id===id);if(!b)return;
 $('inspector').innerHTML=`<p class="eyebrow">SELECTED PROCESS</p><h3>${esc(b.label)}</h3><p>${esc(b.description)}</p><p class="small">Input types → output types</p><div class="signature">${b.inputs.map(p=>esc(p.type)).join(' ⊗ ')}\n→ ${b.outputs.map(p=>esc(p.type)).join(' ⊗ ')}</div><details><summary>Named ports and meanings</summary><h4>Inputs</h4><ul>${b.inputs.map(p=>`<li><code>${esc(p.id)} : ${esc(p.type)}</code> — ${esc(TYPE[p.type])}</li>`).join('')}</ul><h4>Outputs</h4><ul>${b.outputs.map(p=>`<li><code>${esc(p.id)} : ${esc(p.type)}</code> — ${esc(TYPE[p.type])}</li>`).join('')}</ul></details>`;
 document.querySelectorAll('[data-box]').forEach(el=>{const active=el.dataset.box===id;if(el.tagName==='BUTTON')el.setAttribute('aria-pressed',String(active));else el.classList.toggle('selected',active);});
}
function draw(){const expanded=$('expanded').checked;const svg=$('diagram');svg.dataset.expanded=String(expanded);svg.replaceChildren();svg.setAttribute('viewBox',expanded?'0 0 1510 620':'0 0 1220 450');
 const ns='http://www.w3.org/2000/svg';const el=(tag,attrs={},parent=svg,text)=>{const e=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;parent.append(e);return e;};
 const defs=el('defs');const marker=el('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'},defs);el('path',{d:'M0 0L10 5L0 10Z',fill:'#66897e'},marker);
 const positions=expanded?{access:[45,30],'walling/crew':[45,350],'walling/mix':[350,205],'walling/set':[350,400],'walling/wall':[660,230],ready:[965,230],roof:[1265,230]}:{access:[70,40],walling:[385,180],ready:[700,180],roof:[1000,180]};
 const grouped=new Map();current.wires.filter(w=>w.from[0]!=='IN'&&w.to[0]!=='OUT').forEach(w=>{const k=w.from[0]+'|'+w.to[0];if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(w);});
 grouped.forEach(wires=>{const f=wires[0].from[0],t=wires[0].to[0],a=positions[f],b=positions[t];if(!a||!b)return;const x=a[0]+180,y=a[1]+42,tx=b[0],ty=b[1]+42;const bypass=(f==='walling'||f==='walling/wall')&&t==='roof';const sy=bypass?y+55:y,ey=bypass?ty+55:ty;let d=bypass?`M ${x-55} ${sy} C ${x-55} ${sy+155}, ${tx+70} ${ey+155}, ${tx+70} ${ey}`:`M${x} ${y} C${x+80} ${y}, ${tx-80} ${ty}, ${tx} ${ty}`;
 el('path',{d,class:'wire','marker-end':'url(#arrow)'});const types=wires.map(w=>typeAt(w.from));const label=types.join(' · ');const lx=bypass?(x+tx)/2:(x+tx)/2,ly=bypass?sy+120:(y+ty)/2-12;el('text',{x:lx,y:ly,'text-anchor':'middle',class:'wirelabel'},svg,label);
 });
 const ready=positions.ready;el('path',{d:`M${ready[0]+90} ${ready[1]-62} L${ready[0]+90} ${ready[1]-4}`,class:'wire','marker-end':'url(#arrow)'});el('text',{x:ready[0]+90,y:ready[1]-75,'text-anchor':'middle',class:'wirelabel'},svg,'Supplied release evidence');
 if($('fault').value!=='none')el('text',{x:35,y:expanded?595:432,fill:'#9b3328','font-size':14},svg,'Outer input wiring altered: '+$('fault').selectedOptions[0].textContent+'. See the exact wire table below.');
 current.boxes.forEach(b=>{const pos=positions[b.id];if(!pos)return;const g=el('g',{class:'node','data-box':b.id,role:'button',tabindex:0,'aria-label':`Inspect ${b.label}`});el('rect',{x:pos[0],y:pos[1],width:180,height:84,rx:10},g);const words=b.id==='walling'?['Walling','One Storey']:b.id==='walling/crew'?['Check two','worker identities']:b.id==='ready'?['Check wall','readiness']:b.id==='roof'?['Put roof on']:b.id==='access'?['Check supplied','access']:b.label==='Set out · revision B only'?['Set out','revision B only']:b.label==='Build wall assembly'?['Build wall','assembly']:[b.label];words.forEach((s,i)=>el('text',{x:pos[0]+90,y:pos[1]+29+i*19,'text-anchor':'middle'},g,s));el('text',{x:pos[0]+90,y:pos[1]+73,'text-anchor':'middle',class:'subtitle'},g,`${b.inputs.length} inputs → ${b.outputs.length} outputs`);g.addEventListener('click',()=>inspect(b.id));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect(b.id);}});});
 $('diagramTitle').textContent=expanded?'Open the module: the same outer boundary':'One package, several obligations';
}
function render(){const scenario={...DEFAULT_SCENARIO,...Object.fromEntries(fields.map(k=>[k,$(k).checked])),revision:$('revision').value,evidenceRevision:$('revision').value};
 current=buildDiagram({expanded:$('expanded').checked,fault:$('fault').value,replacement:$('replacement').value});const syntax=validate(current);const result=run(current,scenario);
 $('result').classList.toggle('bad',!result.ok);$('result').innerHTML=`<strong>${!syntax.ok?'Wiring rejected':result.ok?'Model accepts a roofed structural shell':'Wiring fits; the model rejects this handoff'}</strong><p>${syntax.ok?'Every port is connected once, types match, and the diagram is acyclic.':'The altered diagram fails a structural check.'}</p>${result.errors.length?`<ul>${result.errors.map(e=>`<li>${esc(e)}</li>`).join('')}</ul>`:'<p>The supplied conditions admit this boundary result. Both worker identities, the peg kit, drawing and access are returned.</p>'}`;
 $('houseRoof').setAttribute('fill',result.ok?'#638d82':'#cdd5d9');$('houseBadge').textContent=result.ok?'✓':'?';$('houseCaption').textContent=result.ok?'Accepted by the teaching model — not engineering approval.':'The selected model has no accepted roofed-shell output.';
 $('trace').innerHTML=result.trace.length?result.trace.map(row=>`<li class="${row.status==='fail'?'fail':''}"><b>${row.status==='pass'?'✓':row.status==='fail'?'×':'—'} ${esc(row.label)}</b>${esc(row.detail)}</li>`).join(''):'<li>Fix the wiring before interpreting its behaviour.</li>';
 $('boxButtons').innerHTML=current.boxes.map(b=>`<button data-box="${esc(b.id)}" aria-pressed="false">${esc(b.label)}</button>`).join('');$('boxButtons').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>inspect(b.dataset.box)));
 $('inputs').innerHTML=current.inputs.map(p=>`<li>${esc(p.label)} <code>${esc(p.type)}</code></li>`).join('');$('outputs').innerHTML=current.outputs.map(p=>`<li>${esc(p.label)} <code>${esc(p.type)}</code></li>`).join('');
 $('wires').innerHTML=current.wires.map(w=>`<tr><td>${esc(endpointLabel(w.from))}</td><td><code>${esc(typeAt(w.from))}</code></td><td>${esc(endpointLabel(w.to))}</td></tr>`).join('');$('outputRecord').textContent=result.ok?JSON.stringify(result.outputs,null,2):'No accepted outer output for this input assignment.';
 draw();if(!current.boxes.some(b=>b.id===selected))selected=$('expanded').checked?'walling/wall':'walling';inspect(selected);$('verification').textContent='Compare the expanded and collapsed boundary results over the model’s finite fixture family.';
}
[...fields,'expanded','replacement','revision','fault'].forEach(id=>$(id).addEventListener('change',render));
$('reset').addEventListener('click',()=>{fields.forEach(k=>$(k).checked=DEFAULT_SCENARIO[k]);$('expanded').checked=false;$('replacement').value='standard';$('revision').value='A';$('fault').value='none';selected='walling';render();});
$('verify').addEventListener('click',()=>{const report=checkEquivalence($('replacement').value);$('verification').textContent=`${report.ok?'PASS':'FAIL'}: ${report.checked} fixture assignments compared; ${report.accepted} accepted and ${report.rejected} rejected. Expanded and collapsed ${report.ok?'agree':'disagree'} on acceptance and the complete outer output. This check uses correct wiring and both drawing/evidence revisions, independently of the currently selected faults. It does not prove arbitrary replacements or physical adequacy.`;});
render();
